const projets = [
  {
    id: 'mayabay',
    titre: 'MAYABAY',
    categorie: 'Design éditorial',
    annee: '2024',
    description: "MayaBay is a restaurant renowned for its Thai and Japanese cuisine and its elegant atmosphere. The story began 19 years ago with the opening of the first restaurant in Monaco. Today, MayaBay is present in Monaco, Courchevel, Dubai and Porto Montenegro, offering a refined dining experience inspired by the flavors of Asia. Where modernity meets tradition.<br><br>In this context, I had to design the new 2026 dedicated cocktail menu. The objective was to structure and highlight the establishment's mixology offering while creating a graphic support consistent with MayaBay's visual identity and atmosphere.",
    credit: "Project designed at Maya Collection",
    images: [
      'assets/projets/mayabay/cover.webp',
      'assets/projets/mayabay/image-1.webp',
      'assets/projets/mayabay/image-2.webp',
      'assets/projets/mayabay/image-3.webp',
      'assets/projets/mayabay/image-4.webp',
      'assets/projets/mayabay/image-5.gif',
      'assets/projets/mayabay/image-6.webp',
      'assets/projets/mayabay/video-1.mp4',
      'assets/projets/mayabay/image-8.webp'
    ],
    video: null,
    galerieGridCount: 4,
    tags: ['Design éditorial', 'Print', 'Direction artistique'],
    couleurAccent: '#d52122',
    behance: 'https://www.behance.net/gallery/245805671/MAYABAY-Cocktail-Menu'
  },
  {
    id: 'fortiche',
    titre: 'FORTICHE',
    categorie: 'Motion Design',
    annee: '2024',
    credit: 'Concept Project',
    description: "Fortiche Production<br>French creative, animation and production company<br><br>Fortiche [fɔʁtiʃ] is a French animation studio founded in 2009, renowned for blending 2D, 3D, and live-action. Known for collaborations with Riot Games, they created Arcane, the acclaimed series based on League of Legends, showcasing their unique style and storytelling.<br><br>As a great admirer of their work, I was deeply inspired to create a reimagined version of their logo with animations. This project is entirely fictional and was carried out as a way to practice my skills.",
    images: [
      'assets/projets/fortiche/cover.webp',
      'assets/projets/fortiche/video-1.mp4',
      'assets/projets/fortiche/image-1.webp',
      'assets/projets/fortiche/image-2.gif',
      'assets/projets/fortiche/image-3.webp',
      'assets/projets/fortiche/video-2.mp4'
    ],
    video: null,
    tags: ['Motion Design', 'Logo', 'Animation'],
    couleurAccent: '#d52122',
    behance: 'https://www.behance.net/gallery/212726607/FORTICHE'
  },
  {
    id: 'flow',
    titre: 'Flow',
    categorie: 'Identité visuelle',
    annee: '2023',
    credit: 'Concept Project',
    description: "Flow®<br>London-based racing bicycles brand<br><br>Flow® is a London-based brand specializing in the design and manufacturing of high-performance racing bicycles. Known for their cutting-edge engineering, Flow® embodies innovation and speed in the cycling world.<br><br>For this project, I developed Flow's visual identity, aiming to reflect their commitment to precision, performance, and modern design. This work showcases the brand's core values and its dynamic presence in the world of competitive cycling.",
    images: [
      'assets/projets/flow/cover.webp',
      'assets/projets/flow/image-1.webp',
      'assets/projets/flow/image-2.webp',
      'assets/projets/flow/image-3.webp',
      'assets/projets/flow/image-4.gif',
      'assets/projets/flow/image-5.webp',
      'assets/projets/flow/image-6.webp',
      'assets/projets/flow/image-7.webp',
      'assets/projets/flow/video-1.mp4'
    ],
    video: null,
    tags: ['Branding', 'Identité visuelle', 'Vélo'],
    couleurAccent: '#d52122',
    behance: 'https://www.behance.net/gallery/185278633/Flow'
  },
  {
    id: 'fanal-forest',
    titre: 'Fanal Forest',
    categorie: 'Photographie',
    annee: '2024',
    credit: 'Photography Collection',
    description: "MADEIRA<br>The Fanal Forest<br><br>Here are the most beautiful photos I was able to take during my stay in Madeira. This is the Fanal forest located in Seixal. The atmosphere is so mystical and calm, with a thick fog hanging through it, and cows have taken up residence there. It's a timeless place, and I was able to capture these photos which perfectly convey the moment.",
    galerieGridCount: 14,
    imagePositions: { 7: 'top center' },
    images: [
      'assets/projets/fanal-forest/cover.webp',
      'assets/projets/fanal-forest/image-1.webp',
      'assets/projets/fanal-forest/image-2.webp',
      'assets/projets/fanal-forest/image-3.webp',
      'assets/projets/fanal-forest/image-4.webp',
      'assets/projets/fanal-forest/image-5.webp',
      'assets/projets/fanal-forest/image-6.webp',
      'assets/projets/fanal-forest/image-7.webp',
      'assets/projets/fanal-forest/image-8.webp',
      'assets/projets/fanal-forest/image-9.webp',
      'assets/projets/fanal-forest/image-10.webp',
      'assets/projets/fanal-forest/image-11.webp',
      'assets/projets/fanal-forest/image-12.webp',
      'assets/projets/fanal-forest/image-13.webp',
      'assets/projets/fanal-forest/image-14.webp'
    ],
    video: null,
    tags: ['Photographie', 'Paysage', 'Madère'],
    couleurAccent: '#d52122',
    behance: 'https://www.behance.net/gallery/181942251/The-Fanal-Forest-Madeira-Photography'
  },
  {
    id: 'sro-festival-2024',
    titre: 'SRO FESTIVAL 2024',
    categorie: 'Photographie',
    annee: '2024',
    credit: 'Photography Collection',
    galerieGridCount: 4,
    description: "Reportage photographique du SRO Festival 2024 — ambiance motorsport, machines et moments d'exception.",
    images: [
      'assets/projets/sro-festival-2024/cover.webp',
      'assets/projets/sro-festival-2024/image-1.webp',
      'assets/projets/sro-festival-2024/image-2.webp',
      'assets/projets/sro-festival-2024/image-3.webp',
      'assets/projets/sro-festival-2024/image-4.webp'
    ],
    video: null,
    tags: ['Photographie', 'Motorsport', 'Événement'],
    couleurAccent: '#d52122',
    behance: 'https://www.behance.net/gallery/222431469/SRO-FESTIVAL-2024'
  },
  {
    id: 'zero',
    titre: 'ZERO',
    categorie: 'Identité visuelle',
    annee: '2024',
    credit: 'Concept Project',
    description: "ZERO™<br><br>ZERO™ is a minimalist and ethical coffee shop based in the Principality of Monaco. It offers a curated selection of specialty coffees, sourced directly from trusted producers who guarantee both quality and traceability. ZERO™ stands for 0 plastic, 0 artificial additives, and 100% environmental respect.",
    images: [
      'assets/projets/zero/cover.webp',
      'assets/projets/zero/image-1.webp',
      'assets/projets/zero/image-2.webp',
      'assets/projets/zero/image-3.webp',
      'assets/projets/zero/image-4.webp',
      'assets/projets/zero/image-5.webp',
      'assets/projets/zero/image-6.webp',
      'assets/projets/zero/image-7.webp',
      'assets/projets/zero/image-8.webp'
    ],
    video: null,
    tags: ['Identité visuelle', 'Minimal'],
    couleurAccent: '#d52122',
    behance: 'https://www.behance.net/gallery/227111473/ZERO'
  },
  {
    id: 'china-2024',
    titre: 'CHINA 2024',
    categorie: 'Photographie',
    annee: '2024',
    credit: 'Photography Collection',
    description: "CHINA 2024<br><br>Here are the most beautiful pictures I was able to take during my stay in China. During this time, I visited a bunch of different places in Beijing, Shanghai, Suzhou, and Hangzhou. This country is so beautiful and full of culture, and people are incredibly kind.<br><br>Through my lens, I wanted to capture the essence of China, the contrast between ancient traditions and modern innovations, the vibrant street life, the peaceful landscapes, and the rich architectural heritage. From the Hutong to the serene gardens of Suzhou, every moment was an opportunity to tell a story.<br><br>This collection is a glimpse into my journey, a visual diary of emotions, encounters, and unforgettable experiences. I hope these photos inspire you to explore and appreciate the beauty of this amazing country.",
    galerieGrids: [
      { start: 1, count: 8, cols: 2, natural: true },
      { start: 9, count: 3, cols: 3, natural: true },
      { start: 12, count: 4, cols: 2, natural: true },
      { start: 16, count: 3, cols: 3, natural: true },
      { start: 19, count: 2, cols: 2, natural: true }
    ],
    coverImages: [2, 4, 8, 12, 15, 16, 18, 19],
    images: [
      'assets/projets/china-2024/cover.webp',
      'assets/projets/china-2024/image-1.webp',
      'assets/projets/china-2024/image-2.webp',
      'assets/projets/china-2024/image-3.webp',
      'assets/projets/china-2024/image-4.webp',
      'assets/projets/china-2024/image-5.webp',
      'assets/projets/china-2024/image-6.webp',
      'assets/projets/china-2024/image-7.webp',
      'assets/projets/china-2024/image-8.webp',
      'assets/projets/china-2024/image-9.webp',
      'assets/projets/china-2024/image-10.webp',
      'assets/projets/china-2024/image-11.webp',
      'assets/projets/china-2024/image-12.webp',
      'assets/projets/china-2024/image-13.webp',
      'assets/projets/china-2024/image-14.webp',
      'assets/projets/china-2024/image-15.webp',
      'assets/projets/china-2024/image-16.webp',
      'assets/projets/china-2024/image-17.webp',
      'assets/projets/china-2024/image-18.webp',
      'assets/projets/china-2024/image-19.webp',
      'assets/projets/china-2024/image-20.webp'
    ],
    video: null,
    tags: ['Photographie', 'Voyage', 'Chine'],
    couleurAccent: '#d52122',
    behance: 'https://www.behance.net/gallery/219983921/CHINA-2024-Photography'
  },
  {
    id: 'atlas',
    titre: 'ATLAS',
    categorie: 'Identité visuelle',
    annee: '2024',
    credit: 'Concept Project',
    description: "ATLAS®<br>Mountaineering brand<br><br>Atlas® is a brand dedicated to the world of mountaineering, climbing and alpine exploration. Specializing in equipment and gear, Atlas® empowers adventurers to push their limits and embrace the challenges of the mountain.<br><br>For this project, I had to create Atlas' logo and my goal was to capture its commitment to precision, resilience and sharpness.",
    images: [
      'assets/projets/atlas/cover.webp',
      'assets/projets/atlas/image-1.webp',
      'assets/projets/atlas/image-2.webp',
      'assets/projets/atlas/image-3.webp',
      'assets/projets/atlas/image-4.webp'
    ],
    video: null,
    tags: ['Identité visuelle', 'Typographie'],
    couleurAccent: '#d52122',
    behance: 'https://www.behance.net/gallery/214756767/ATLAS'
  }
];
